import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { repositoryRoot } from "../lib/config.js";

export interface RoleSource {
  /** The file stem, which is also the role's short name: `engineer`, `butler`. */
  slug: string;
  frontmatter: string;
  title: string;
  body: string;
}

export const BASELINE_HEADING = "## The shared baseline";
export const ROLE_PREFIX = "openjii-role-";

const GENERATED_NOTE = "Generated by pnpm roles:generate. Edit the source under .agents/roles/.";

export function splitFrontmatter(text: string): { frontmatter: string; rest: string } {
  const match = /^---\n([\s\S]*?)\n---\n/.exec(text);
  if (!match) throw new Error("expected a frontmatter block delimited by ---");
  return { frontmatter: match[1], rest: text.slice(match[0].length).replace(/^\n+/, "") };
}

export function splitTitle(text: string): { title: string; body: string } {
  const match = /^# (.+)\n/.exec(text);
  if (!match) throw new Error("expected the body to start with a level-one heading");
  return { title: match[1].trim(), body: text.slice(match[0].length).replace(/^\n+/, "") };
}

/**
 * Pushes every heading in `body` one level deeper, so the baseline's own sections nest under the
 * heading that introduces them. Lines inside a fenced block are left alone.
 */
export function demoteHeadings(body: string): string {
  let fenced = false;

  return body
    .split("\n")
    .map((line) => {
      if (line.startsWith("```")) {
        fenced = !fenced;
        return line;
      }
      if (fenced) return line;
      return /^#{1,5} /.test(line) ? `#${line}` : line;
    })
    .join("\n");
}

export function parseRole(slug: string, text: string): RoleSource {
  const { frontmatter, rest } = splitFrontmatter(text);
  const { title, body } = splitTitle(rest);
  return { slug, frontmatter, title, body };
}

export function renderRoleSkill(role: RoleSource, baselineBody: string): string {
  return [
    "---",
    role.frontmatter,
    "---",
    "",
    `<!-- ${GENERATED_NOTE} -->`,
    "",
    `# ${role.title}`,
    "",
    role.body.trimEnd(),
    "",
    BASELINE_HEADING,
    "",
    demoteHeadings(baselineBody).trimEnd(),
    "",
  ].join("\n");
}

export function rolesDirectory(root: string): string {
  return join(root, ".agents", "roles");
}

export function skillDirectory(root: string, slug: string): string {
  return join(root, ".agents", "skills", `${ROLE_PREFIX}${slug}`);
}

export async function readBaseline(root: string): Promise<string> {
  const text = await readFile(join(rolesDirectory(root), "baseline.md"), "utf8");
  return splitTitle(text).body;
}

export async function readRoles(root: string): Promise<RoleSource[]> {
  const entries = await readdir(rolesDirectory(root));
  const slugs = entries
    .filter((entry) => entry.endsWith(".md") && entry !== "baseline.md")
    .map((entry) => entry.replace(/\.md$/, ""))
    .sort();

  return Promise.all(
    slugs.map(async (slug) => {
      const text = await readFile(join(rolesDirectory(root), `${slug}.md`), "utf8");
      return parseRole(slug, text);
    }),
  );
}

async function run(): Promise<number> {
  const root = repositoryRoot();
  const baseline = await readBaseline(root);
  const roles = await readRoles(root);

  for (const role of roles) {
    const directory = skillDirectory(root, role.slug);
    await mkdir(directory, { recursive: true });
    await writeFile(join(directory, "SKILL.md"), renderRoleSkill(role, baseline), "utf8");
    process.stdout.write(`wrote ${ROLE_PREFIX}${role.slug}/SKILL.md\n`);
  }

  process.stdout.write(`${roles.length} role skills generated\n`);
  return 0;
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  process.exitCode = await run();
}
