import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  demoteHeadings,
  parseRole,
  renderRoleSkill,
  splitFrontmatter,
  splitTitle,
} from "./generate-roles.js";
import { checkRoles, prosePoliceFindings, titleCaseHeadings } from "./roles-check.js";

const root = fileURLToPath(new URL("../../../..", import.meta.url));

const source = `---
name: openjii-role-example
description: An example.
---

# Example

Body text.

## A section

More text.
`;

describe("splitFrontmatter", () => {
  it("separates the frontmatter from the body", () => {
    const { frontmatter, rest } = splitFrontmatter(source);

    expect(frontmatter).toContain("name: openjii-role-example");
    expect(rest.startsWith("# Example")).toBe(true);
  });

  it("refuses a file with no frontmatter", () => {
    expect(() => splitFrontmatter("# No frontmatter\n")).toThrow("frontmatter");
  });
});

describe("splitTitle", () => {
  it("takes the level-one heading as the title", () => {
    const { title, body } = splitTitle("# Engineer\n\nWork.\n");

    expect(title).toBe("Engineer");
    expect(body).toBe("Work.\n");
  });

  it("refuses a body that does not start with a heading", () => {
    expect(() => splitTitle("Work.\n")).toThrow("level-one heading");
  });
});

describe("demoteHeadings", () => {
  it("pushes every heading one level deeper", () => {
    expect(demoteHeadings("## Two\n\n### Three\n")).toBe("### Two\n\n#### Three\n");
  });

  it("leaves a comment inside a fenced block alone", () => {
    const text = "## Two\n\n```bash\n# not a heading\n```\n\n## Also two\n";

    expect(demoteHeadings(text)).toBe("### Two\n\n```bash\n# not a heading\n```\n\n### Also two\n");
  });
});

describe("renderRoleSkill", () => {
  const rendered = renderRoleSkill(
    parseRole("example", source),
    "Shared text.\n\n## Safety\n\nCare.\n",
  );

  it("keeps the source frontmatter verbatim", () => {
    expect(
      rendered.startsWith("---\nname: openjii-role-example\ndescription: An example.\n---"),
    ).toBe(true);
  });

  it("says it is generated and where the source is", () => {
    expect(rendered).toContain("Generated by pnpm roles:generate");
    expect(rendered).toContain(".agents/roles/");
  });

  it("puts the role before the baseline", () => {
    expect(rendered.indexOf("Body text.")).toBeLessThan(rendered.indexOf("Shared text."));
  });

  it("nests the baseline's own sections under the baseline heading", () => {
    expect(rendered).toContain("## The shared baseline");
    expect(rendered).toContain("### Safety");
    expect(rendered).not.toContain("\n## Safety");
  });

  it("is deterministic", () => {
    expect(renderRoleSkill(parseRole("example", source), "Shared text.\n")).toBe(
      renderRoleSkill(parseRole("example", source), "Shared text.\n"),
    );
  });
});

describe("titleCaseHeadings", () => {
  it("flags a capitalised function word", () => {
    expect(titleCaseHeadings("## Adding A New Feature\n")).toEqual(["Adding A New Feature"]);
    expect(titleCaseHeadings("## Doing The Thing\n")).toEqual(["Doing The Thing"]);
  });

  it("flags three or more capitalised words with no function word", () => {
    expect(titleCaseHeadings("## Known Debt Register\n")).toEqual([]);
    expect(titleCaseHeadings("## Known Debt Register Rules\n")).toEqual([
      "Known Debt Register Rules",
    ]);
  });

  it("accepts sentence case, and proper nouns", () => {
    expect(titleCaseHeadings("## Adding a new feature\n")).toEqual([]);
    expect(titleCaseHeadings("## Working with Databricks\n")).toEqual([]);
    expect(titleCaseHeadings("## Reading Linear and GitHub\n")).toEqual([]);
    expect(titleCaseHeadings("## Talking to AWS\n")).toEqual([]);
  });
});

describe("prosePoliceFindings", () => {
  it("catches a dash, a title-case heading and a chatbot phrase", () => {
    const findings = prosePoliceFindings(
      "x",
      "## Doing The Thing\n\nGreat question, use a — dash.\n",
    );

    expect(findings.map((finding) => finding.detail.split(":")[0])).toEqual(
      expect.arrayContaining(["dash"]),
    );
    expect(findings.some((finding) => finding.detail.includes("sentence case"))).toBe(true);
    expect(findings.some((finding) => finding.detail.includes("chatbot phrase"))).toBe(true);
  });

  it("passes clean prose", () => {
    expect(prosePoliceFindings("x", "## Doing the thing\n\nIt works.\n")).toEqual([]);
  });
});

describe("the committed roles", () => {
  it("have generated skills and symlinks that match their sources", async () => {
    await expect(checkRoles(root)).resolves.toEqual([]);
  });
});
