import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { envManifest } from "./env-manifest.js";
import type { EnvTarget } from "./env-manifest.js";

const root = fileURLToPath(new URL("../../..", import.meta.url));

const localNotes = new Map([
  ["COOKIE_DOMAIN", "Leave unset for localhost sessions and passkey validation."],
  ["EMAIL_SERVER", "No local SMTP service listens on this address."],
  ["MAILCHIMP_API_KEY", "Mailchimp keys are all-or-none; leave all unset locally."],
  ["AWS_LAMBDA_FUNCTION_NAME", "Leave unset outside Lambda."],
]);

export function renderEnvExample(target: EnvTarget): string {
  const entries = envManifest.filter((entry) => entry.targets.includes(target));
  const output = [
    "# Generated by pnpm --filter @repo/devkit env:generate. Do not edit by hand.",
    "# Safe local defaults intentionally degrade external integrations.",
  ];

  for (const entry of entries.filter((entry) => entry.sentinel !== undefined)) {
    const note = localNotes.get(entry.key);
    if (note) output.push(`# ${note}`);
    output.push(`${entry.key}=${entry.sentinel}`);
  }

  const deliberatelyUnset = entries.filter((entry) => entry.local === "must-be-unset");
  if (deliberatelyUnset.length > 0) {
    output.push("", "# Deliberately absent locally (do not add dummy values):");
    for (const entry of deliberatelyUnset) {
      const note = localNotes.get(entry.key);
      output.push(`# - ${entry.key}${note ? `: ${note}` : ""}`);
    }
  }

  return `${output.join("\n")}\n`;
}

async function writeEnvExamples(): Promise<void> {
  await Promise.all([
    writeFile(`${root}/apps/backend/.env.example`, renderEnvExample("backend")),
    writeFile(`${root}/apps/web/.env.example`, renderEnvExample("web")),
  ]);
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  await writeEnvExamples();
}
