packages:
  - "apps/*"
  - "apps/tools/*"
  - "packages/*"
  - "tooling/*"

patchedDependencies:
  react-native-usb-serialport-for-android: patches/react-native-usb-serialport-for-android.patch

catalog:
  typescript: ^5.8.3
  zod: ^3.24.3
  eslint: ^9.25.1
  prettier: ^3.5.3
  react-hook-form: ^7.56.2
  tailwindcss: ^3.4.15
  "@types/node": ^22.15.3

catalogs:
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.2
    "@types/react-dom": ^19.1.3
  react19-mobile:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.0
    "@types/react-dom": 19.0.0
