packages:
  - "apps/*"
  - "apps/tools/*"
  - "packages/*"

patchedDependencies:
  react-native-usb-serialport-for-android: patches/react-native-usb-serialport-for-android.patch

catalog:
  typescript: ^5.8.3
  zod: ^3.24.3
