packages:
  - apps/*
  - apps/tools/*
  - packages/*
  - tooling/*

catalog:
    
  # Dev tooling
  eslint: ^9.25.1
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.5.4

  # Misc
  zod: ^3.24.3
  dotenv: ^16.5.0

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": 19.1.0
    "@types/react-dom": 19.1.0
  node22:
    "@types/node": 22.15.3

