packages:
  - "apps/*"
  - "apps/tools/*"
  - "packages/*"
  - "tooling/*"

patchedDependencies:
  react-native-usb-serialport-for-android: patches/react-native-usb-serialport-for-android.patch

catalog:
  typescript: ^5.8.3
  zod: ^3.24.3
  eslint: ^9.25.1
  prettier: ^3.5.3
