packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

patchedDependencies:
  react-native-usb-serialport-for-android: patches/react-native-usb-serialport-for-android.patch

catalog:
  axios: ^1.13.5
  typescript: ^5.8.3
  zod: ^3.24.3
  eslint: ^9.25.1
  prettier: ^3.5.3
  react-hook-form: ^7.56.2
  tailwindcss: ^3.4.15
  "@types/node": ^22.15.3
  nodemailer: ^7.0.11
  "@types/nodemailer": ^7.0.9
  posthog-js: ^1.279.1
  posthog-node: ^5.10.2
  next: ^15.5.10

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4
  react-query:
    "@tanstack/react-query": ^5.84.1
    "@tanstack/react-query-devtools": ^5.84.1
    "@tanstack/query-async-storage-persister": ^5.83.1
    "@tanstack/react-query-persist-client": ^5.84.1
  testing:
    vitest: ^3.2.4
    jsdom: ^26.0.0
    "@vitest/coverage-v8": ^3.2.4
    "@vitest/ui": ^3.2.4
    "@testing-library/react": ^16.3.0
    "@testing-library/jest-dom": ^6.6.8
    "@testing-library/user-event": ^14.6.1
    "@vitejs/plugin-react": ^4.3.4
  aws-sdk:
    "@aws-sdk/client-cognito-identity": ^3.995.0
    "@aws-sdk/client-location": ^3.995.0
