packages:
  - "apps/*"
  - "apps/tools/*"
  - "packages/*"
  - "tooling/*"

patchedDependencies:
  react-native-usb-serialport-for-android: patches/react-native-usb-serialport-for-android.patch

catalog:
  typescript: ^5.8.3
  zod: ^3.24.3
  eslint: ^9.25.1
  prettier: ^3.5.3
  react-hook-form: ^7.56.2
  tailwindcss: ^3.4.15
  "@types/node": ^22.15.3
  nodemailer: ^7.0.4
  "@types/nodemailer": ^6.4.17

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4
  react-email:
    react-email: "4.1.3"
    "@react-email/components": ^0.3.1
  react-query:
    "@tanstack/react-query": ^5.84.1
    "@tanstack/react-query-devtools": ^5.84.1
    "@tanstack/query-async-storage-persister": ^5.83.1
    "@tanstack/react-query-persist-client": ^5.84.1
  testing:
    vitest: ^3.2.4
    jsdom: ^26.0.0
    "@vitest/coverage-istanbul": ^3.2.4
    "@vitest/ui": ^3.2.4
    "@testing-library/react": ^16.3.0
    "@testing-library/jest-dom": ^6.6.8
    "@vitejs/plugin-react": ^4.3.4
