name: "OpenTofu Format Check"
description: "Runs OpenTofu fmt -check to verify HCL formatting"

inputs:
  continue-on-error:
    description: "Whether to continue on error"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: OpenTofu Fmt Check
      shell: bash
      working-directory: infrastructure/env/${{ env.environment }}
      run: tofu fmt -check
      continue-on-error: ${{ inputs.continue-on-error }}
