import type { Metadata } from "next";
import Image from "next/image";

import "./globals.css";

export const metadata: Metadata = {
  title: "Jan IngenHousz Institute",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="pl-20 ml-10 mt-20">
            <Image src="/jan-ingenhousz-institute-logo-header.png" alt="Jan IngenHousz Institute Logo" width={250} height={58} loading={"eager"} />
          </div>
          <h1 className="text-3xl font-bold underline">Jan IngenHousz</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
