version: "3.8"

services:
  backend:
    build:
      context: ../../
      dockerfile: apps/backend/Dockerfile
    container_name: openjii-backend
    ports:
      - "3020:3020"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - openjii-network

  postgres:
    extends:
      file: ../../packages/database/docker-compose.yml
      service: postgres
    networks:
      - openjii-network

networks:
  openjii-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
