name: "Build Packages"
description: "Builds affected packages"

runs:
  using: "composite"
  steps:
    - name: Build Apps
      shell: bash
      run: |
        echo "🔨 Building affected packages"
        # Build command with individual --filter flags for each package
        BUILD_CMD="pnpm turbo run build"
        cat affected_apps.json | jq -r '.[]' | while read -r APP; do
          BUILD_CMD="$BUILD_CMD --filter=$APP"
        done
        echo "Running: $BUILD_CMD"
        eval "$BUILD_CMD"
