name: "Build Packages"
description: "Builds affected packages"

inputs:
  affected_apps:
    description: "JSON array of affected app names"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Apps
      shell: bash
      run: |
        echo "🔨 Building affected packages"
        AFFECTED_APPS='${{ inputs.affected_apps }}'
        
        # Log the affected apps for debugging
        echo "Affected apps value:"
        echo "$AFFECTED_APPS"
        echo "Affected apps parsed:"
        echo "$AFFECTED_APPS" | jq '.'
        
        # Build command with individual --filter flags for each package
        BUILD_CMD="pnpm turbo run build"
        echo $AFFECTED_APPS | jq -r '.[]' | while read -r APP; do
          BUILD_CMD="$BUILD_CMD --filter=$APP"
        done
        echo "Running: $BUILD_CMD"
        eval "$BUILD_CMD"
