services:
  postgres:
    image: postgres:15
    ports:
      - "5837:5432" # expose pg on port 5837 to not collide with pg from elsewhere
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  postgres_data:
    driver: local
