services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create-additional-databases.sh:/docker-entrypoint-initdb.d/create-additional-databases.sh
    environment:
      POSTGRES_DB: openjii_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_CREATE_ADDITIONAL_DATABASES: openjii_local_test

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 25s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
