name: "Lint Packages"
description: "Lints affected packages"

inputs:
  affected_apps:
    description: "JSON array of affected app names"
    required: true

runs:
  using: "composite"
  steps:
    - name: Lint Code
      shell: bash
      run: |
        echo "🔎 Linting affected packages"
        AFFECTED_APPS='${{ inputs.affected_apps }}'
        
        # Lint command with individual --filter flags for each package
        LINT_CMD="pnpm turbo run lint"
        echo $AFFECTED_APPS | jq -r '.[]' | while read -r APP; do
          LINT_CMD="$LINT_CMD --filter=$APP"
        done
        echo "Running: $LINT_CMD"
        eval "$LINT_CMD"
