import { defineRules } from "../rule.js";

export const docsRules = defineRules([
  {
    id: "docs.generated-specs",
    surface: "docs",
    category: "keep-generated-history",
    granularity: "file",
    paths: ["apps/docs/openapi.json", "apps/docs/public/asyncapi.yaml", "asyncapi.yaml"],
    disposition: "regenerate",
    target: "generated API and AsyncAPI specifications",
    rationale: "Generated specifications change only through their source generators.",
    compatibilityBoundary: "generated API contracts",
  },
  {
    id: "docs.graphify-cache",
    surface: "docs",
    category: "keep-generated-history",
    granularity: "path",
    paths: ["apps/docs/content/developers/graphify-out/**"],
    disposition: "regenerate",
    target: "generated Graphify cache",
    rationale:
      "The tracked cache is generated documentation tooling output and is not hand-edited.",
    compatibilityBoundary: "generated documentation index",
    coversContents: true,
  },
  {
    id: "docs.multispeq-product-guides",
    surface: "docs",
    category: "keep-product-specific",
    granularity: "path",
    paths: [
      "apps/docs/content/developers/multispeq-mqtt-tool/**",
      "apps/docs/content/guide/devices-protocols/multispeq.mdx",
    ],
    disposition: "preserve",
    target: "MultiSpeQ product and MQTT-tool documentation",
    rationale: "These guides intentionally document a concrete product and its dedicated tool.",
    compatibilityBoundary: "published product instructions and MQTT examples",
    coversContents: true,
  },
  {
    id: "docs.product-media-metadata",
    surface: "docs",
    category: "keep-product-specific",
    granularity: "file",
    paths: [
      "apps/docs/media/mobile/**",
      "apps/docs/public/img/guide/web/capture-metadata.json",
      "apps/docs/scripts/validate-deployment.mjs",
    ],
    disposition: "preserve",
    target: "MultiSpeQ-specific captured media metadata and route validation",
    rationale: "The metadata truthfully records product-specific captured evidence and routes.",
    compatibilityBoundary: "published media evidence",
  },
  {
    id: "docs.multispeq-product-examples",
    surface: "docs",
    category: "keep-product-specific",
    granularity: "content-pattern",
    paths: [
      "README.md",
      "apps/docs/content/developers/architecture/index.mdx",
      "apps/docs/content/developers/contributing/index.mdx",
      "apps/docs/content/developers/index.mdx",
      "apps/docs/content/developers/meta.json",
      "apps/docs/content/guide/data-analysis/viewing-data.mdx",
      "apps/docs/content/guide/devices-protocols/continuous-sensors.mdx",
      "apps/docs/content/guide/devices-protocols/index.mdx",
      "apps/docs/content/guide/devices-protocols/meta.json",
      "apps/docs/content/guide/devices-protocols/multi-device.mdx",
      "apps/docs/content/guide/get-started/index.mdx",
      "apps/docs/content/guide/get-started/key-concepts.mdx",
      "apps/docs/content/guide/get-started/quick-start.mdx",
      "apps/docs/content/guide/measuring/index.mdx",
      "apps/docs/content/guide/measuring/taking-measurements.mdx",
      "apps/docs/content/guide/reference/faq.mdx",
      "apps/docs/content/guide/reference/glossary.mdx",
    ],
    pattern: "multispeq",
    disposition: "preserve",
    target: "MultiSpeQ named as the actual supported handheld product and its dedicated MQTT tool",
    rationale:
      "The surrounding prose is device-first; each MultiSpeQ mention is an accurate product example, product-catalog entry, taxonomy value, or reference to the dedicated MultiSpeQ MQTT tool, not a generic device stand-in.",
    compatibilityBoundary: "published product instructions and navigation",
  },
  {
    id: "docs.design-decisions-history",
    surface: "docs",
    category: "keep-compatibility",
    granularity: "content-pattern",
    paths: [
      "apps/docs/content/developers/design-decisions/macro-sandbox-adr.mdx",
      "apps/docs/content/developers/design-decisions/mqtt-topic-proposal.mdx",
    ],
    pattern: "multispeq",
    disposition: "preserve",
    target: "historical ADR/proposal terminology and MQTT topic-value examples",
    rationale:
      "These records document a removed in-process executor path and a `sensorType` topic-value example of their time; hand-editing them would falsify the historical record.",
    compatibilityBoundary: "design decision history and MQTT topic values",
  },
  {
    id: "docs.design-history",
    surface: "docs",
    category: "keep-compatibility",
    granularity: "content-pattern",
    paths: ["docs/ojd-1565-dynamic-scan-timeout-proposal.md"],
    pattern: "multispeq",
    disposition: "preserve",
    target: "historical design proposal terminology",
    rationale: "Checked-in proposals record the context and compatibility behavior of their time.",
    compatibilityBoundary: "design decision history",
  },
]);
