import { defineRules } from "../rule.js";

export const mobileRules = defineRules([
  {
    id: "mobile.deny-retired-multispeq-communication-path",
    kind: "denylist",
    surface: "mobile",
    category: "rename-neutral",
    granularity: "path",
    paths: ["apps/mobile/**"],
    pattern: "apps/mobile/src/features/connection/services/multispeq-communication",
    disposition: "rename",
    target: "apps/mobile/src/features/connection/services/multispeq",
    rationale:
      "The retired mixed contract/product path must not return after the neutral executor contract was separated from the MultiSpeQ implementation.",
    compatibilityBoundary: null,
  },
  {
    id: "mobile.deny-retired-multispeq-executor-contract",
    kind: "denylist",
    surface: "mobile",
    category: "rename-neutral",
    granularity: "symbol-key",
    paths: ["apps/mobile/**"],
    pattern: "IMultispeqCommandExecutor",
    disposition: "rename",
    target: "DeviceCommandExecutor",
    rationale:
      "Generic consumers use the neutral executor contract; the concrete MultiSpeQ class remains explicitly product-specific.",
    compatibilityBoundary: null,
  },
  {
    id: "mobile.family-values",
    surface: "mobile",
    category: "keep-compatibility",
    granularity: "content-pattern",
    paths: [
      "apps/mobile/src/features/connection/services/mobile-runtime-support.ts",
      "apps/mobile/src/features/connection/services/multispeq/mock-device/create-mock-command-executor.ts",
      "apps/mobile/src/features/measurement-flow/screens/measurement-flow-screen/components/flow-nodes/utils/evaluate-and-route.ts",
    ],
    pattern: "multispeq",
    disposition: "preserve",
    target: "multispeq runtime family value and pre-identity fallback",
    rationale:
      "Mobile's only current executable family remains MultiSpeQ; routing and workbook fallback values are load-bearing.",
    compatibilityBoundary: "runtime family and workbook $device value",
  },
  {
    id: "mobile.multispeq-runtime-adapter-references",
    surface: "mobile",
    category: "keep-product-specific",
    granularity: "content-pattern",
    paths: [
      "apps/mobile/src/features/connection/hooks/use-device-connection.ts",
      "apps/mobile/src/features/connection/services/device-connection-manager/device-connection.ts",
      "apps/mobile/src/features/connection/services/device-connection-manager/device-queries.ts",
    ],
    pattern: "multispeq",
    disposition: "preserve",
    target: "explicit references from generic dispatch to the current MultiSpeQ adapter",
    rationale:
      "The generic connection boundary explicitly selects its only current product executor and product fixtures without implying support for another family.",
    compatibilityBoundary: "current mobile execution support",
  },
  {
    id: "mobile.multispeq-product-path",
    surface: "mobile",
    category: "keep-product-specific",
    granularity: "path",
    paths: ["apps/mobile/src/features/connection/services/multispeq/**"],
    pattern: "multispeq",
    disposition: "preserve",
    target: "MultiSpeQ implementation boundary",
    rationale:
      "This product subpath owns the concrete MultiSpeQ executor, transports, framing behavior, and product mocks.",
    compatibilityBoundary: "firmware framing, device signatures, and telemetry",
  },
  {
    id: "mobile.multispeq-product-implementation",
    surface: "mobile",
    category: "keep-product-specific",
    granularity: "content-pattern",
    paths: [
      "apps/mobile/src/features/connection/services/multispeq/**",
      "apps/mobile/src/features/connection/services/device-connection-manager/device-sort.ts",
      "apps/mobile/src/features/connection/services/device-connection-manager/device-utils.ts",
      "apps/mobile/src/features/measurement-flow/domain/flow-transitions.ts",
      "apps/mobile/src/features/measurement-flow/screens/measurement-flow-screen/components/flow-nodes/measurement-node/components/scanning-state.tsx",
      "apps/mobile/CONTEXT.md",
    ],
    pattern: "multispeq",
    disposition: "preserve",
    target: "MultiSpeQ detection, execution, wire behavior, and raw result documentation",
    rationale:
      "These references describe the product actually driven by mobile rather than a generic device contract.",
    compatibilityBoundary: "driver behavior, firmware protocol, and result shape",
  },
  {
    id: "mobile.multispeq-telemetry",
    surface: "mobile",
    category: "keep-compatibility",
    granularity: "content-pattern",
    paths: [
      "apps/mobile/src/shared/observability/trace.ts",
      "apps/mobile/src/features/connection/services/multispeq/multispeq-command-executor.ts",
    ],
    pattern: '(?:multispeq\\.command|\\[multispeq\\]|multispeq-cmd|createLogger\\("multispeq"\\))',
    disposition: "preserve",
    target: "multispeq.command telemetry and logger identity",
    rationale:
      "These exact identities describe the concrete implementation and may feed historical observability.",
    compatibilityBoundary: "telemetry event and logger identity",
  },
  {
    id: "mobile.product-fixtures",
    surface: "mobile",
    category: "fixture",
    granularity: "file",
    paths: ["apps/mobile/src/**/*.test.ts", "apps/mobile/src/**/*.test.tsx"],
    disposition: "fixture-only",
    target: "intentional MultiSpeQ device, family, and protocol fixtures",
    rationale:
      "Mobile tests model the only currently supported product and protect its compatibility values.",
    compatibilityBoundary: null,
  },
  {
    id: "mobile.product-assets",
    surface: "mobile",
    category: "keep-product-specific",
    granularity: "file",
    paths: [
      "apps/mobile/assets/multispeq2-button.png",
      "apps/mobile/assets/multispeq2-microusb.png",
    ],
    disposition: "preserve",
    target: "MultiSpeQ hardware instruction assets",
    rationale: "These images depict physical MultiSpeQ controls and connectors.",
    compatibilityBoundary: "product instruction media",
  },
]);
