import { defineRules } from "../rule.js";

export const toolingRules = defineRules([
  {
    id: "tooling.device-nomenclature-self",
    surface: "tooling",
    category: "fixture",
    granularity: "path",
    paths: ["tooling/device-nomenclature/**"],
    disposition: "fixture-only",
    target: "scanner rules and isolated fixtures",
    rationale:
      "The scanner necessarily names MultiSpeQ while describing and testing nomenclature rules.",
    compatibilityBoundary: null,
    coversContents: true,
  },
  {
    id: "tooling.support-catalog-product-specific",
    surface: "tooling",
    category: "keep-product-specific",
    granularity: "file",
    paths: ["tooling/device-nomenclature/src/support-catalog.ts"],
    disposition: "preserve",
    target: "current per-host product support taxonomy",
    rationale:
      "The support catalog is normative taxonomy that records real per-product host support states; its MultiSpeQ references name a current product, not an isolated fixture.",
    compatibilityBoundary: "per-host product support taxonomy",
  },
  {
    id: "tooling.conformance-taxonomy-compatibility",
    surface: "tooling",
    category: "keep-compatibility",
    granularity: "file",
    paths: ["tooling/device-nomenclature/src/conformance.test.ts"],
    disposition: "preserve",
    target: "cross-package taxonomy conformance assertions",
    rationale:
      "The conformance suite asserts current API/DB/IoT taxonomy equality and product invariants; its MultiSpeQ references are compatibility checks, not product fixtures.",
    compatibilityBoundary: "API/DB/IoT taxonomy equality",
  },
  {
    id: "tooling.infrastructure-docs",
    surface: "tooling",
    category: "keep-compatibility",
    granularity: "content-pattern",
    paths: [
      "infrastructure/README.md",
      "infrastructure/modules/iot-core/README.md",
      "infrastructure/modules/kinesis/README.md",
      "infrastructure/modules/timestream/README.md",
    ],
    pattern: "multispeq",
    disposition: "preserve",
    target: "MultiSpeQ topic and infrastructure examples",
    rationale:
      "Infrastructure documentation records current topic and sensor-family compatibility values.",
    compatibilityBoundary: "MQTT topic and sensor family values",
  },
  {
    id: "deny.retired-generic-identifier",
    kind: "denylist",
    surface: "tooling",
    category: "rename-neutral",
    granularity: "symbol-key",
    paths: ["apps/**", "packages/**"],
    pattern: "genericMultispeqDevice",
    disposition: "rename",
    target: "genericDevice",
    rationale: "This exact generic identifier incorrectly hard-codes one product.",
    compatibilityBoundary: null,
  },
  {
    id: "deny.retired-generic-translation-key",
    kind: "denylist",
    surface: "tooling",
    category: "rename-neutral",
    granularity: "symbol-key",
    paths: ["apps/**", "packages/**"],
    pattern: "device.genericMultispeq",
    disposition: "rename",
    target: "semantic device key",
    rationale: "This exact retired key encodes a product in generic device copy.",
    compatibilityBoundary: null,
  },
  {
    id: "deny.retired-generic-path",
    kind: "denylist",
    surface: "tooling",
    category: "rename-neutral",
    granularity: "path",
    paths: ["apps/mobile/**"],
    pattern: "apps/mobile/src/features/connection/multispeq",
    disposition: "rename",
    target: "apps/mobile/src/features/connection/device",
    rationale: "The exact retired path would place generic connection ownership under one product.",
    compatibilityBoundary: null,
  },
]);
