import { defineRules } from "../rule.js";

export const webRules = defineRules([
  {
    id: "web.multispeq-pipeline",
    surface: "web",
    category: "keep-product-specific",
    granularity: "path",
    paths: ["apps/web/lib/multispeq/**"],
    disposition: "preserve",
    target: "MultiSpeQ protocol detection and processing pipeline",
    rationale: "This path implements actual MultiSpeQ protocol behavior.",
    compatibilityBoundary: "protocol execution behavior",
    coversContents: true,
  },
  {
    id: "web.family-values",
    surface: "web",
    category: "keep-compatibility",
    granularity: "content-pattern",
    paths: [
      "apps/web/components/workbook/add-cell-button.tsx",
      "apps/web/components/workbook/cells/output-cell-timeseries.tsx",
      "apps/web/components/workbook/cells/output-cell.tsx",
      "apps/web/components/workbook/protocol-picker.tsx",
      "apps/web/components/workbook/workbook-editor.tsx",
      "apps/web/components/workbook/workbook-header.tsx",
      "apps/web/hooks/iot/device-type-mapping.ts",
      "apps/web/hooks/iot/useIotCommunication/useIotCommunication.ts",
      "apps/web/hooks/iot/useIotProtocolExecution/useIotProtocolExecution.ts",
      "apps/web/hooks/workbook/useWorkbookExecution/useWorkbookExecution.ts",
      "apps/web/util/sensor-family.ts",
      "packages/i18n/locales/de-DE/experiments.json",
      "packages/i18n/locales/de-DE/navigation.json",
      "packages/i18n/locales/en-US/experiments.json",
      "packages/i18n/locales/en-US/navigation.json",
      "packages/i18n/locales/nl-NL/experiments.json",
      "packages/i18n/locales/nl-NL/navigation.json",
    ],
    pattern: "[\"']multispeq[\"']",
    caseSensitive: true,
    disposition: "preserve",
    target: "multispeq API and driver family value",
    rationale: "Host routing and API family strings are compatibility values.",
    compatibilityBoundary: "API family and local driver routing",
  },
  {
    id: "web.product-fixtures",
    surface: "web",
    category: "fixture",
    granularity: "file",
    paths: [
      "apps/web/**/*.test.ts",
      "apps/web/**/*.test.tsx",
      "apps/web/lib/iot/mock-devices.ts",
      "apps/web/test/factories.ts",
    ],
    disposition: "fixture-only",
    target: "MultiSpeQ web product and compatibility fixtures",
    rationale: "Web tests intentionally model product identity, protocols, and current routing.",
    compatibilityBoundary: null,
  },
  {
    id: "web.multispeq-specific-implementation",
    surface: "web",
    category: "keep-product-specific",
    granularity: "content-pattern",
    paths: [
      "apps/web/components/workbook/cells/output-cell-timeseries.tsx",
      "apps/web/components/workbook/cells/output-cell.tsx",
      "apps/web/hooks/iot/useIotBrowserSupport.ts",
      "apps/web/hooks/iot/useIotCommunication/useIotCommunication.ts",
      "apps/web/hooks/iot/useIotProtocolExecution/useIotProtocolExecution.ts",
    ],
    pattern: "multispeq",
    disposition: "preserve",
    target: "MultiSpeQ driver, wire-shape, capability, and output pipeline implementation",
    rationale:
      "These references select or describe actual MultiSpeQ-specific drivers, protocol wire shapes, transport capabilities, output detection, and timeseries processing. Quoted family values remain classified by the narrower compatibility rule.",
    compatibilityBoundary: "product-specific protocol execution and output rendering",
  },
  {
    id: "web.product-locale-copy",
    surface: "web",
    category: "keep-product-specific",
    granularity: "content-pattern",
    paths: [
      "packages/i18n/locales/de-DE/experiments.json",
      "packages/i18n/locales/de-DE/navigation.json",
      "packages/i18n/locales/en-US/experiments.json",
      "packages/i18n/locales/en-US/navigation.json",
      "packages/i18n/locales/nl-NL/experiments.json",
      "packages/i18n/locales/nl-NL/navigation.json",
    ],
    pattern: "MultiSpeQ",
    caseSensitive: true,
    disposition: "preserve",
    target: "canonical MultiSpeQ product upload and navigation labels",
    rationale:
      "These choices refer to the actual MultiSpeQ product and retain its canonical trademark spelling.",
    compatibilityBoundary: null,
  },
]);
