import { describe, expect, it } from "vitest";

import { checkBody, checkTitle, splitSections } from "./ticket-standard.js";

const workItem = `## User story

**WHO:** A researcher browsing any of the five resource lists.

**WHAT:** They click a header to sort.

**WHY:** No list can be sorted today.

## Acceptance criteria

- Every column Postgres already provides can be sorted.
- The sort is part of the URL, so a refresh opens the same order.

## Dependencies and risks

None.

## Additional context

The precedent is \`OverviewTable\`.

## How it was built

## Testing criteria
`;

function rules(body: string): string[] {
  return checkBody(body).findings.map((finding) => finding.rule);
}

describe("splitSections", () => {
  it("keys content by the ## heading above it and trims it", () => {
    expect(splitSections("## A\n\nx\n\n## B\n")).toEqual([
      { heading: "A", content: "x" },
      { heading: "B", content: "" },
    ]);
  });
});

describe("checkBody", () => {
  it("passes a work item in the agreed shape", () => {
    const report = checkBody(workItem);

    expect(report.shape).toBe("work-item");
    expect(report.findings).toEqual([]);
    expect(report.budget).toBe(1200);
    expect(report.longestBullet).toBe(14);
  });

  it("counts characters without the two developer sections, which carry their own limit", () => {
    const filled = workItem.replace(
      "## How it was built\n",
      `## How it was built\n\n${"x".repeat(1100)}\n`,
    );
    const over = workItem.replace(
      "## Testing criteria\n",
      `## Testing criteria\n\n${"x".repeat(1200)}\n`,
    );

    expect(checkBody(filled).characters).toBe(checkBody(workItem).characters);
    expect(rules(filled)).toEqual([]);
    expect(checkBody(over).findings).toContainEqual({
      rule: "dev-section",
      detail: "Testing criteria is 1200 characters; the limit is 1200",
    });
  });

  it("fails a body over budget", () => {
    const long = workItem.replace("None.", "n".repeat(1200));

    expect(rules(long)).toContain("budget");
  });

  it("fails a bullet of 25 words or more, naming its first words", () => {
    const long = workItem.replace(
      "- Every column Postgres already provides can be sorted.",
      `- ${Array.from({ length: 25 }, (_, i) => `w${i}`).join(" ")}`,
    );
    const finding = checkBody(long).findings.find((f) => f.rule === "bullet");

    expect(finding?.detail).toContain("25 words");
    expect(finding?.detail).toContain("w0 w1 w2");
  });

  it("names missing and unexpected headings", () => {
    const wrong = workItem.replace("## Additional context", "## Context");
    const finding = checkBody(wrong).findings.find((f) => f.rule === "headings");

    expect(finding?.detail).toBe('missing "Additional context"; unexpected "Context"');
  });

  it("reports out-of-order headings as such", () => {
    const swapped = workItem
      .replace(
        "## Dependencies and risks\n\nNone.\n\n## Additional context",
        "## Additional context",
      )
      .replace(
        "The precedent is `OverviewTable`.\n\n## How it was built",
        "The precedent is `OverviewTable`.\n\n## Dependencies and risks\n\nNone.\n\n## How it was built",
      );

    expect(checkBody(swapped).findings).toContainEqual({
      rule: "headings",
      detail: "headings are out of order",
    });
  });

  it("fails em and en dashes, banners, and a second contrast sentence", () => {
    const dashed = workItem.replace("None.", "None — really.");
    const banner = workItem.replace("None.", "This was generated by AI during triage.");
    const contrast = workItem.replace("None.", "Sort, not filter. Facets, not operators.");

    expect(rules(dashed)).toContain("dash");
    expect(rules(banner)).toContain("banner");
    expect(rules(contrast)).toContain("contrast");
    expect(rules(workItem.replace("None.", "Sort, not filter."))).toEqual([]);
  });

  it("fails a bullet or a WHO line that does not end as a sentence, and a semicolon chain", () => {
    const fragment = workItem.replace(
      "- Every column Postgres already provides can be sorted.",
      "- Sortable: name, status, updated. Confirm",
    );
    const chain = workItem.replace(
      "- Every column Postgres already provides can be sorted.",
      "- Facets: experiments status; protocols family; macros language.",
    );
    const why = workItem.replace("**WHY:** No list can be sorted today.", "**WHY:** no sorting");
    const quoted = workItem.replace(
      "- Every column Postgres already provides can be sorted.",
      "- The precedent is `OverviewTable`.",
    );

    expect(checkBody(fragment).findings).toContainEqual({
      rule: "sentence",
      detail: 'does not end as a sentence: "Sortable: name, status, updated. Confirm..."',
    });
    expect(checkBody(chain).findings.map((f) => f.rule)).toContain("sentence");
    expect(checkBody(why).findings).toContainEqual({
      rule: "sentence",
      detail: "WHY does not end as a sentence",
    });
    expect(rules(quoted)).toEqual([]);
  });

  it("wants WHO, WHAT and WHY and non-empty acceptance criteria on a work item", () => {
    const noWhy = workItem.replace("**WHY:** No list can be sorted today.\n", "");
    const noCriteria = workItem.replace(
      "- Every column Postgres already provides can be sorted.\n- The sort is part of the URL, so a refresh opens the same order.\n",
      "",
    );

    expect(checkBody(noWhy).findings).toContainEqual({
      rule: "persona",
      detail: "User story has no **WHY:** line",
    });
    expect(rules(noCriteria)).toContain("gate");
  });

  it("recognises the other shapes by their first heading", () => {
    const bug =
      "## Observed\n\nx\n\n## Expected\n\ny\n\n## Reproduction\n\n1. Open the list.\n\n## Environment\n\ndev\n\n## Evidence\n\nnone\n\n## How it was built\n\n## Testing criteria\n";
    const spike =
      "## Question\n\nq\n\n## Why now\n\nw\n\n## Timebox\n\n2 days\n\n## Done when\n\nan ADR\n";
    const project =
      "## Problem\n\np\n\n## Outcome\n\no\n\n## Non-goals\n\nn\n\n## Design\n\nd\n\n## Deliverables\n\nt\n\n## Done when\n\nc\n\n## Risks and dependencies\n\nr\n";

    expect(checkBody(bug)).toMatchObject({ shape: "bug", budget: 800, findings: [] });
    expect(checkBody(spike)).toMatchObject({ shape: "spike", budget: 600, findings: [] });
    expect(checkBody(project)).toMatchObject({ shape: "project", budget: 2500, findings: [] });
    expect(rules(spike.replace("an ADR", ""))).toContain("gate");
  });

  it("reports an unknown first heading as a shape failure", () => {
    expect(checkBody("## Contract\n\nx\n").findings).toEqual([
      { rule: "shape", detail: 'first heading "Contract" matches no ticket or project shape' },
    ]);
  });
});

describe("checkTitle", () => {
  it("limits length and refuses a type prefix", () => {
    expect(checkTitle("Researcher can sort any resource list")).toEqual([]);
    expect(checkTitle("x".repeat(70)).map((f) => f.rule)).toEqual(["title"]);
    expect(checkTitle("DISCOVERY: platform search").map((f) => f.detail)).toEqual([
      "starts with a type prefix; that is a label",
    ]);
  });
});
