name: "OpenTofu Plan"
description: "Runs OpenTofu plan"
runs:
  using: "composite"
  steps:
    - name: Resolve Environment
      shell: bash
      run: |
        if [[ "${{ env.environment }}" == "prod" ]]; then
          echo "RESOLVED_ENV=prod" >> "$GITHUB_ENV"
        else
          echo "RESOLVED_ENV=dev" >> "$GITHUB_ENV"
        fi
    - name: OpenTofu Plan
      shell: bash
      working-directory: infrastructure/env/${{ env.RESOLVED_ENV }}
      run: |
        exec 2>&1
        tofu plan 
