name: "OpenTofu Plan"
description: "Runs OpenTofu plan"
runs:
  using: "composite"
  steps:
    - name: OpenTofu Plan
      shell: bash
      working-directory: infrastructure/env/${{ env.environment }}
      run: |
        exec 2>&1
        tofu plan 
