name: "Test Packages"
description: "Tests affected packages"

inputs:
  affected_apps:
    description: "JSON array of affected app names"
    required: true
  codecov-token:
    description: "Codecov token for uploading coverage"
    required: true
  skip-coverage:
    description: "Skip coverage upload (e.g., for Dependabot PRs)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Run Tests
      id: run-tests
      shell: bash
      run: |
        echo "ðŸ§ª Testing affected packages"

        AFFECTED_APPS='${{ inputs.affected_apps }}'
        APPS=($(echo $AFFECTED_APPS | jq -r '.[]'))

        TEST_CMD="pnpm turbo run test"
        for APP in "${APPS[@]}"; do
          TEST_CMD="$TEST_CMD --filter=$APP"
        done

        echo "Running: $TEST_CMD"

        OUTPUT=$(eval "$TEST_CMD" 2>&1)
        EXIT_CODE=$?
        echo "$OUTPUT"

        COVERAGE_FILES=$(find apps tooling packages -maxdepth 2 -name "coverage.json" -type f 2>/dev/null)

        if [ -z "$COVERAGE_FILES" ]; then
          echo "âš ï¸ No coverage files were generated; skipping Codecov upload"
          echo "has_coverage=false" >> $GITHUB_OUTPUT
        else
          echo "âœ… Found coverage files:"
          echo "$COVERAGE_FILES"
          echo "has_coverage=true" >> $GITHUB_OUTPUT
        fi

        exit $EXIT_CODE

    - name: Upload coverage to Codecov
      if: inputs.skip-coverage != 'true' && steps.run-tests.outputs.has_coverage == 'true'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.codecov-token }}
        files: apps/*/coverage.json,tooling/*/coverage.json,packages/*/coverage.json
        flags: affected
        fail_ci_if_error: true
        verbose: true
        override_branch: ${{ github.head_ref }}
        override_commit: ${{ github.event.pull_request.head.sha }}
        override_pr: ${{ github.event.number }}
