name: "Test Packages"
description: "Tests affected packages"

runs:
  using: "composite"
  steps:
    - name: Run Tests
      shell: bash
      run: |
        echo "🧪 Testing affected packages"
        # Test command with individual --filter flags for each package
        TEST_CMD="pnpm turbo run test"
        cat affected_apps.json | jq -r '.[]' | while read -r APP; do
          TEST_CMD="$TEST_CMD --filter=$APP"
        done
        echo "Running: $TEST_CMD"
        eval "$TEST_CMD"
