name: "Test Packages"
description: "Tests affected packages"

inputs:
  affected_apps:
    description: "JSON array of affected app names"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Tests
      shell: bash
      run: |
        echo "🧪 Testing affected packages"
        AFFECTED_APPS='${{ inputs.affected_apps }}'
        
        # Test command with individual --filter flags for each package
        TEST_CMD="pnpm turbo run test"
        echo $AFFECTED_APPS | jq -r '.[]' | while read -r APP; do
          TEST_CMD="$TEST_CMD --filter=$APP"
        done
        echo "Running: $TEST_CMD"
        eval "$TEST_CMD"
