name: Build Android App Bundle (AAB)

on:
  workflow_dispatch:

jobs:
  build-aab:
    runs-on: ubuntu-latest
    container:
      image: openjdk:17-jdk
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          
      - name: Setup Expo CLI
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          
      - name: Install dependencies
        run: |
          cd ../..
          pnpm install
          cd apps/mobile
        
      - name: Build Android App Bundle
        run: |
          echo 'node-linker=hoisted' > .npmrc
          eas build --platform android --profile production --local
          rm .npmrc
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: |
            *.aab
            *.apk
          retention-days: 30
