name: Development Deployment

on:
  push:
    branches:
      - main
jobs:
  Deploy-Development:
    uses: ./.github/workflows/deployment-template.yml
    with:
      environment: dev
    secrets: inherit
    permissions:
      id-token: write # Grant the required permission
      # contents: read # Ensure the workflow can read repository contents

      