name: Development Deployment

on:
  push:
    branches:
      - main
jobs:
  Deploy-Development:
    uses: ./.github/workflows/deployment-template.yml
    with:
      environment: dev
    secrets: inherit
