name: Run Database Migrations

on:
  push:
    branches:
      - main
    paths:
      - "packages/database/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment for migrations"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  migrate:
    name: Run Drizzle Migrations
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Download Infrastructure Outputs
        uses: actions/download-artifact@v4
        with:
          name: tofu-outputs-${{ inputs.environment || 'dev' }}
          path: tofu-outputs/

      - name: Get Database Credentials
        id: db-creds
        uses: ./.github/actions/get-database-credentials
        with:
          environment: ${{ inputs.environment || 'dev' }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Dependencies
        run: |
          # Install dependencies using pnpm with workspace support
          pnpm install --frozen-lockfile

      - name: Build Database Package
        run: |
          # Build the database package
          pnpm run build --filter=database

      - name: Run Drizzle Migrations
        env:
          # Use the safely masked database URL from the composite action
          DATABASE_URL: ${{ steps.db-creds.outputs.database-url }}
        working-directory: packages/database
        run: |
          echo "Running database migrations for environment: ${{ inputs.environment || 'dev' }}"
          pnpm run db:migrate

      - name: Migration Summary
        run: |
          echo "=== Migration Summary ==="
          echo "Environment: ${{ inputs.environment || 'dev' }}"
          echo "Database: ${{ steps.db-creds.outputs.database-name }} at ${{ steps.db-creds.outputs.database-host }}"
          echo "Migration completed successfully!"
